### PR TITLE
fix bug where hidden variables show up in groups/filters when checkin…

### LINKED ISSUE #138: Hidden variables show up in group/filter list via the settings screen.

### PR DESCRIPTION
**Pull request by samussiah**
…g group/filter boxes on the settings tab of hidden variables

Closes #138

### CODE REVIEW

**Comment by samussiah** [comment]
Assign class of _hidden to group `option`s and filter `li`s on `update()`.

File: src/codebook/settings/updateSettings/reset.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+export default function reset(codebook) {
```
Comment (jwildfire) [inline src/codebook/settings/updateSettings/reset.js]: nice. created #144 for a future release.
