### PR TITLE
Fixed width

### LINKED ISSUE #62: Strange behavior on re-size
Charts are rendering outside of their wrapper. 

screen shot 2017-04-14 at 2 43 48 pm

### PR DESCRIPTION
**Pull request by jwildfire**
fixes #62. merge after #67.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { charts } from "./charts";
 
 export default {
   createCodebook: createCodebook,
+  createChart: createCodebook,
```
Comment (samussiah) [inline src/index.js]: ?
