### PR TITLE
Cbrt bug

### LINKED ISSUE #14: Math.cbrt() not supported in IE

### PR DESCRIPTION
**Pull request by jwildfire**
Fix #14. Renders as expected in IE after the fix. Merge after #67.

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ import { charts } from "./charts";
 
 export default {
   createCodebook: createCodebook,
+  createChart: createCodebook,
```
Comment (samussiah) [inline src/index.js]: Why?
